// Generated contract bindings for Silent Loan Circle
// This file would normally be generated by the Compact compiler

const ledger = (data) => {
  // Mock ledger implementation
  return {
    circleState: data.circleState || 0,
    memberCount: data.memberCount || 0,
    currentCycleIndex: data.currentCycleIndex || 0,
    payoutPointer: data.payoutPointer || 0,
    contributionAmount: data.contributionAmount || 0,
    maxMembers: data.maxMembers || 0,
    totalContributed: data.totalContributed || 0,
    contributionsReceived: data.contributionsReceived || 0,
    admin: data.admin || '0x0000000000000000000000000000000000000000'
  };
};

module.exports = { ledger };
